version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    image: supportable/bot:local
    container_name: supportable_bot
    restart: no
    stop_grace_period: 15s
    environment:
      - NODE_ENV=production
